// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/user/get": {
            "get": {
                "description": "用于获取用户信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "获取用户信息接口",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "授权令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/contexts.RESPONSE"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "$ref": "#/definitions/contexts.UserData"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/user/insert": {
            "post": {
                "description": "用于新增用户信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "新增用户信息接口",
                "parameters": [
                    {
                        "description": "用户信息",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contexts.UserInsertRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "授权令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/contexts.RESPONSE"
                        }
                    }
                }
            }
        },
        "/api/user/list": {
            "get": {
                "description": "用于获取用户列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "获取用户列表接口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "账户",
                        "name": "account",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "状态 1:启用 2:禁用 默认:1",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页数 默认:1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页数量 默认:20",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "授权令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/contexts.RESPONSE"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "Data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/contexts.UserData"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/user/login": {
            "post": {
                "description": "用于登录admin",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "登录接口",
                "parameters": [
                    {
                        "description": "登录参数",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contexts.UserLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/contexts.UserLoginResponse"
                        }
                    }
                }
            }
        },
        "/api/user/remove": {
            "post": {
                "description": "用于删除用户",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "删除用户接口",
                "parameters": [
                    {
                        "description": "用户id信息",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contexts.RemoveRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "授权令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/contexts.RESPONSE"
                        }
                    }
                }
            }
        },
        "/api/user/removes": {
            "post": {
                "description": "用于批量删除用户",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "批量删除用户接口",
                "parameters": [
                    {
                        "description": "用户ids信息",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contexts.RemovesRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "授权令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/contexts.RESPONSE"
                        }
                    }
                }
            }
        },
        "/api/user/status": {
            "post": {
                "description": "用于更新用户状态",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "更新用户状态接口",
                "parameters": [
                    {
                        "description": "用户状态信息",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contexts.StatusRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "授权令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/contexts.RESPONSE"
                        }
                    }
                }
            }
        },
        "/api/user/update": {
            "post": {
                "description": "用于更新用户信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户相关"
                ],
                "summary": "更新用户信息接口",
                "parameters": [
                    {
                        "description": "用户信息",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/contexts.UserUpdateRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "授权令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/contexts.RESPONSE"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "contexts.RESPONSE": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态码 0:成功 非0:失败 失败可直接提示msg信息",
                    "type": "integer",
                    "default": 0
                },
                "data": {
                    "description": "数据 成功返回指定数据 失败返回nil"
                },
                "msg": {
                    "description": "状态信息",
                    "type": "string",
                    "default": "success"
                }
            }
        },
        "contexts.RemoveRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "用户ID",
                    "type": "integer"
                }
            }
        },
        "contexts.RemovesRequest": {
            "type": "object",
            "properties": {
                "ids": {
                    "description": "用户IDS",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "contexts.StatusRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "用户ID",
                    "type": "integer"
                },
                "status": {
                    "description": "状态 1:启用 2:禁用",
                    "type": "integer"
                }
            }
        },
        "contexts.UserData": {
            "type": "object",
            "properties": {
                "account": {
                    "description": "账户",
                    "type": "string"
                },
                "id": {
                    "description": "id",
                    "type": "integer"
                },
                "insert_at": {
                    "description": "入库时间",
                    "type": "string"
                },
                "status": {
                    "description": "状态 1:启用 2:禁用",
                    "type": "integer"
                },
                "update_at": {
                    "description": "更新时间",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "contexts.UserInsertRequest": {
            "type": "object",
            "properties": {
                "account": {
                    "description": "账户",
                    "type": "string"
                },
                "confirmPassword": {
                    "description": "确认密码",
                    "type": "string"
                },
                "isDelete": {
                    "description": "是否删除 1:是 0:否",
                    "type": "integer",
                    "default": 2
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "salt": {
                    "description": "盐",
                    "type": "string"
                },
                "status": {
                    "description": "状态 1:启用 2:禁用",
                    "type": "integer",
                    "default": 2
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "contexts.UserLoginRequest": {
            "type": "object",
            "properties": {
                "account": {
                    "description": "账号",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                }
            }
        },
        "contexts.UserLoginResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态码 0:成功 非0:失败 失败可直接提示msg信息",
                    "type": "integer",
                    "default": 0
                },
                "data": {
                    "description": "数据",
                    "type": "object",
                    "properties": {
                        "authorization": {
                            "description": "登录授权令牌",
                            "type": "string"
                        }
                    }
                },
                "msg": {
                    "description": "状态信息",
                    "type": "string",
                    "default": "success"
                }
            }
        },
        "contexts.UserUpdateRequest": {
            "type": "object",
            "properties": {
                "account": {
                    "description": "账户",
                    "type": "string"
                },
                "confirmPassword": {
                    "description": "确认密码",
                    "type": "string"
                },
                "id": {
                    "description": "用户ID",
                    "type": "integer"
                },
                "isDelete": {
                    "description": "是否删除 1:是 0:否",
                    "type": "integer",
                    "default": 2
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
