definitions:
  contexts.RESPONSE:
    properties:
      code:
        default: 0
        description: 状态码 0:成功 非0:失败 失败可直接提示msg信息
        type: integer
      data:
        description: 数据 成功返回指定数据 失败返回nil
      msg:
        default: success
        description: 状态信息
        type: string
    type: object
  contexts.RemoveRequest:
    properties:
      id:
        description: 用户ID
        type: integer
    type: object
  contexts.RemovesRequest:
    properties:
      ids:
        description: 用户IDS
        items:
          type: integer
        type: array
    type: object
  contexts.StatusRequest:
    properties:
      id:
        description: 用户ID
        type: integer
      status:
        description: 状态 1:启用 2:禁用
        type: integer
    type: object
  contexts.UserData:
    properties:
      account:
        description: 账户
        type: string
      id:
        description: id
        type: integer
      insert_at:
        description: 入库时间
        type: string
      status:
        description: 状态 1:启用 2:禁用
        type: integer
      update_at:
        description: 更新时间
        type: string
      username:
        description: 用户名
        type: string
    type: object
  contexts.UserInsertRequest:
    properties:
      account:
        description: 账户
        type: string
      confirmPassword:
        description: 确认密码
        type: string
      isDelete:
        default: 2
        description: 是否删除 1:是 0:否
        type: integer
      password:
        description: 密码
        type: string
      salt:
        description: 盐
        type: string
      status:
        default: 2
        description: 状态 1:启用 2:禁用
        type: integer
      username:
        description: 用户名
        type: string
    type: object
  contexts.UserLoginRequest:
    properties:
      account:
        description: 账号
        type: string
      password:
        description: 密码
        type: string
    type: object
  contexts.UserLoginResponse:
    properties:
      code:
        default: 0
        description: 状态码 0:成功 非0:失败 失败可直接提示msg信息
        type: integer
      data:
        description: 数据
        properties:
          authorization:
            description: 登录授权令牌
            type: string
        type: object
      msg:
        default: success
        description: 状态信息
        type: string
    type: object
  contexts.UserUpdateRequest:
    properties:
      account:
        description: 账户
        type: string
      confirmPassword:
        description: 确认密码
        type: string
      id:
        description: 用户ID
        type: integer
      isDelete:
        default: 2
        description: 是否删除 1:是 0:否
        type: integer
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    type: object
info:
  contact: {}
paths:
  /api/user/get:
    get:
      description: 用于获取用户信息
      parameters:
      - description: 用户ID
        in: query
        name: id
        required: true
        type: integer
      - description: 授权令牌
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/contexts.RESPONSE'
            - properties:
                Data:
                  $ref: '#/definitions/contexts.UserData'
              type: object
      summary: 获取用户信息接口
      tags:
      - 用户相关
  /api/user/insert:
    post:
      description: 用于新增用户信息
      parameters:
      - description: 用户信息
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/contexts.UserInsertRequest'
      - description: 授权令牌
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/contexts.RESPONSE'
      summary: 新增用户信息接口
      tags:
      - 用户相关
  /api/user/list:
    get:
      description: 用于获取用户列表
      parameters:
      - description: 账户
        in: query
        name: account
        type: string
      - description: 状态 1:启用 2:禁用 默认:1
        in: query
        name: status
        type: integer
      - description: 页数 默认:1
        in: query
        name: page
        type: integer
      - description: 页数量 默认:20
        in: query
        name: limit
        type: integer
      - description: 授权令牌
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/contexts.RESPONSE'
            - properties:
                Data:
                  items:
                    $ref: '#/definitions/contexts.UserData'
                  type: array
              type: object
      summary: 获取用户列表接口
      tags:
      - 用户相关
  /api/user/login:
    post:
      consumes:
      - application/json
      description: 用于登录admin
      parameters:
      - description: 登录参数
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/contexts.UserLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/contexts.UserLoginResponse'
      summary: 登录接口
      tags:
      - 用户相关
  /api/user/remove:
    post:
      description: 用于删除用户
      parameters:
      - description: 用户id信息
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/contexts.RemoveRequest'
      - description: 授权令牌
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/contexts.RESPONSE'
      summary: 删除用户接口
      tags:
      - 用户相关
  /api/user/removes:
    post:
      description: 用于批量删除用户
      parameters:
      - description: 用户ids信息
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/contexts.RemovesRequest'
      - description: 授权令牌
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/contexts.RESPONSE'
      summary: 批量删除用户接口
      tags:
      - 用户相关
  /api/user/status:
    post:
      description: 用于更新用户状态
      parameters:
      - description: 用户状态信息
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/contexts.StatusRequest'
      - description: 授权令牌
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/contexts.RESPONSE'
      summary: 更新用户状态接口
      tags:
      - 用户相关
  /api/user/update:
    post:
      description: 用于更新用户信息
      parameters:
      - description: 用户信息
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/contexts.UserUpdateRequest'
      - description: 授权令牌
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/contexts.RESPONSE'
      summary: 更新用户信息接口
      tags:
      - 用户相关
swagger: "2.0"
